# Generated by Django 4.1.12 on 2024-06-10 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay_name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=255)),
                ('crop_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_description', models.TextField()),
                ('is_owner', models.BooleanField(default=False)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_tenant', models.BooleanField(default=False)),
                ('tenant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_maintainer', models.BooleanField(default=False)),
                ('maintainer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('farm_type', models.CharField(choices=[('upload', 'Upload'), ('lowland', 'Lowland')], default='lowland', max_length=10)),
                ('farm_crop', models.CharField(choices=[('monocrop', 'Monocrop'), ('intercrop', 'Intercrop')], default='intercrop', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('extension_name', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateTimeField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6)),
                ('civil_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('annulled', 'Annulled')], default='single', max_length=10)),
                ('citizenship', models.CharField(choices=[('natural_born', 'Natural Born'), ('dual_by_birth', 'Dual by Birth'), ('dual_by_naturalization', 'Dual by Naturalization')], default='natural_born', max_length=50)),
                ('contact_no', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('facebook_account', models.CharField(blank=True, max_length=255, null=True)),
                ('household_head', models.BooleanField(default=False)),
                ('beneficiary_4p', models.BooleanField(default=False)),
                ('indigenous_group', models.BooleanField(default=False)),
                ('spouse_name', models.CharField(blank=True, max_length=255, null=True)),
                ('spouse_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('member_organization', models.BooleanField(default=False)),
                ('skills', models.TextField(blank=True, null=True)),
                ('pwd', models.BooleanField(default=False)),
                ('education', models.CharField(choices=[('none', 'None'), ('elementary', 'Elementary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary'), ('college_graduate', 'College Graduate'), ('post_graduate', 'Post Graduate')], default='none', max_length=20)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=255)),
                ('region_short', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religion_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tribe_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Purok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purok_name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.barangay')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.region')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileOccupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation_description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.occupation')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='religion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.religion'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tribe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tribe'),
        ),
        migrations.CreateModel(
            name='FarmPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='farm_pictures/')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.farm')),
            ],
        ),
        migrations.CreateModel(
            name='FarmCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crop_qnty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_farming', models.BooleanField(default=True)),
                ('farm_crop_description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.farm')),
            ],
        ),
        migrations.AddField(
            model_name='farm',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profile'),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.province')),
            ],
        ),
        migrations.CreateModel(
            name='Dependents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ext_name', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateTimeField()),
                ('education', models.CharField(choices=[('none', 'None'), ('elementary', 'Elementary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary'), ('college_graduate', 'College Graduate'), ('post_graduate', 'Post Graduate')], default='none', max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CityMunicipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality_name', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.district')),
            ],
        ),
        migrations.AddField(
            model_name='barangay',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.citymunicipality'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=255)),
                ('address_type', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.barangay')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.district')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.citymunicipality')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profile')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.province')),
                ('purok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.purok')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.region')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('user', 'User')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='user_pictures/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
